# Generated by Django 4.1.5 on 2023-01-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=25, unique=True, verbose_name="name"
                    ),
                ),
                ("url", models.URLField(max_length=25, unique=True)),
                (
                    "status",
                    models.CharField(default=None, max_length=999999, null=True),
                ),
                (
                    "reports",
                    models.CharField(default=None, max_length=999999, null=True),
                ),
                ("time", models.CharField(default=None, max_length=999999, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
