# Generated by Django 4.1.5 on 2023-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="name")),
                ("url", models.URLField(max_length=25)),
                (
                    "status",
                    models.CharField(default=None, max_length=999999, null=True),
                ),
                (
                    "reports",
                    models.CharField(default=None, max_length=999999, null=True),
                ),
                ("time", models.CharField(default=None, max_length=999999, null=True)),
            ],
        ),
    ]
