# Generated by Django 4.1.5 on 2023-01-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.FilePathField(null=True, path="/media/"),
        ),
    ]
