# Generated by Django 4.1.5 on 2023-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_model", "0002_service_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                db_index=True, max_length=25, unique=True, verbose_name="name"
            ),
        ),
    ]
