# Generated by Django 4.1.5 on 2023-01-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_model", "0003_alter_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
