# Generated by Django 4.1.5 on 2023-01-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_model", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="tgid",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
