# Generated by Django 4.1.5 on 2023-01-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_model", "0002_remove_user_email_user_tgid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tgid",
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed",
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
