# Generated by Django 4.1.5 on 2023-01-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_model", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="confirmed"),
        ),
    ]
