# Generated by Django 4.1.5 on 2023-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_model", "0003_remove_user_tgid_user_subscribed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="subscribed",
            new_name="subscribes",
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="email"
            ),
        ),
    ]
