# Generated by Django 4.1.5 on 2023-01-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_model", "0004_rename_subscribed_user_subscribes_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tgid",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
