# Generated by Django 4.1.5 on 2023-01-29 18:31

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("user_model", "0005_user_tgid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscribes",
            field=django_mysql.models.ListTextField(
                models.CharField(max_length=100), max_length=999999, null=True, size=6
            ),
        ),
    ]
