# Generated by Django 4.1.5 on 2023-01-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_model", "0006_alter_user_subscribes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscribes",
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
