# Generated by Django 4.1.5 on 2023-02-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="abbreviation",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
