# Generated by Django 4.1.5 on 2023-01-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Raiting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.IntegerField(default=False, null=True)),
                ("message", models.CharField(max_length=200, null=True)),
                ("service_name", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
