# Generated by Django 4.1.5 on 2023-01-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "types",
                    models.CharField(
                        default=False, max_length=200, null=True, verbose_name="types"
                    ),
                ),
                ("message", models.CharField(default=False, max_length=200, null=True)),
                ("is_moderated", models.BooleanField(default=False)),
            ],
        ),
    ]
