# Generated by Django 4.1.5 on 2023-01-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_model", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="types",
            field=models.CharField(max_length=200, null=True, verbose_name="types"),
        ),
    ]
