# Generated by Django 4.1.5 on 2023-01-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "users_name",
                    models.CharField(max_length=25, verbose_name="users_name"),
                ),
                (
                    "types",
                    models.CharField(
                        default=False, max_length=200, null=True, verbose_name="types"
                    ),
                ),
                ("message", models.CharField(default=False, max_length=200, null=True)),
                ("is_moderated", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
