# Generated by Django 4.1.5 on 2023-01-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_model", "0002_alter_report_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="message",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
