# Generated by Django 4.1.5 on 2023-01-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_model", "0003_alter_report_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="service_slug",
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
